name: Build and Deploy to GKE (Production)

on:
  push:
    branches:
      - main

env:
  ARTIFACT_REPO: supplychainvisibilitygcr
  IMAGE_NAME: configmanagementapi
  NODE_ENV: production
  PROJECT_ID: settyl-gcp-infra
  CLUSTER_NAME: supplychainvisibility-gks
  ARTIFACT_REGION: us-east1
  REGION: us-east1
  
jobs:
  build-and-deploy:
    name: Build and Deploy to GKE
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SUPPLYCHAINVISIBILITYDOCKERAUTH }}

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SUPPLYCHAINVISIBILITYDOCKERAUTH }}
          project_id: ${{ env.PROJECT_ID }}

      # Step 4: Install gke-gcloud-auth-plugin
      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components install gke-gcloud-auth-plugin

      # Step 5: Configure Docker for Artifact Registry
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${ARTIFACT_REGION}-docker.pkg.dev

      # Step 6: Build and Push Docker Image
      - name: Build and Push Docker Image
        id: build-image
        run: |
          IMAGE_TAG=${{ github.sha }}  # Using commit SHA for tagging
          docker build -t ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG} .
          docker push ${ARTIFACT_REGION}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.ARTIFACT_REPO }}/${{ env.IMAGE_NAME }}:${IMAGE_TAG}

      # Step 7: Set up GKE context
      - name: Set up GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.CLUSTER_NAME }} \
            --region ${{ env.REGION }} \
            --project ${{ env.PROJECT_ID }}

      # Step 8: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f manifests/production/deployment.yml
          kubectl apply -f manifests/production/service.yml
          kubectl apply -f manifests/production/ingress.yml
          kubectl rollout restart deployment/configmanagementapi -n supplychainvisibility

      # Step 9: Verify Deployment
      - name: Verify Deployment
        run: |
          kubectl get all --all-namespaces

      # Optional: Notify on Deployment Success
      - name: Notify Deployment Success
        if: success()
        run: |
          echo "Deployment to GKE was successfull!"
